//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SorterVisualizer.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesMainWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesMainWindow() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SorterVisualizer.Resources.Localization.MessagesMainWindow", typeof(MessagesMainWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Array is empty.
        /// </summary>
        public static string ArrayEmptyText {
            get {
                return ResourceManager.GetString("ArrayEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Array initialization.
        /// </summary>
        public static string ArrayInitializationText {
            get {
                return ResourceManager.GetString("ArrayInitializationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Array legth.
        /// </summary>
        public static string ArrayLegthText {
            get {
                return ResourceManager.GetString("ArrayLegthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate random array into a database....
        /// </summary>
        public static string CreateRandomArrayText {
            get {
                return ResourceManager.GetString("CreateRandomArrayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error in array inserting into database..
        /// </summary>
        public static string DatabaseArrayInsertingErrorText {
            get {
                return ResourceManager.GetString("DatabaseArrayInsertingErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database connection.
        /// </summary>
        public static string DatabaseConnection {
            get {
                return ResourceManager.GetString("DatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The required database does not exist.
        /// </summary>
        public static string DatabaseDosentExistText {
            get {
                return ResourceManager.GetString("DatabaseDosentExistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database saving.
        /// </summary>
        public static string DatabaseSavingCaption {
            get {
                return ResourceManager.GetString("DatabaseSavingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data.
        /// </summary>
        public static string DataText {
            get {
                return ResourceManager.GetString("DataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fast.
        /// </summary>
        public static string FastText {
            get {
                return ResourceManager.GetString("FastText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From database....
        /// </summary>
        public static string FromDatabaseText {
            get {
                return ResourceManager.GetString("FromDatabaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From file.
        /// </summary>
        public static string FromFileText {
            get {
                return ResourceManager.GetString("FromFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not find selected language in current languages files.
        /// </summary>
        public static string LanguageNotFoundText {
            get {
                return ResourceManager.GetString("LanguageNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Options.
        /// </summary>
        public static string OptionsText {
            get {
                return ResourceManager.GetString("OptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to add this array to database? If you don&apos;t add array to database than information about sorting process will not be inserted to database after sorting..
        /// </summary>
        public static string SaveArrayDialogText {
            get {
                return ResourceManager.GetString("SaveArrayDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Slow.
        /// </summary>
        public static string SlowText {
            get {
                return ResourceManager.GetString("SlowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  finished sorting.
        /// </summary>
        public static string SorterFinishedSortingText {
            get {
                return ResourceManager.GetString("SorterFinishedSortingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sorters list....
        /// </summary>
        public static string SortersListText {
            get {
                return ResourceManager.GetString("SortersListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sorting aborted.
        /// </summary>
        public static string SortingAbortedText {
            get {
                return ResourceManager.GetString("SortingAbortedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sorting complete.
        /// </summary>
        public static string SortingCompleteText {
            get {
                return ResourceManager.GetString("SortingCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot perform this action while sorting is started.
        /// </summary>
        public static string SortingIsStartedWarningText {
            get {
                return ResourceManager.GetString("SortingIsStartedWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sorting process.
        /// </summary>
        public static string SortingProcessCaption {
            get {
                return ResourceManager.GetString("SortingProcessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sorting started....
        /// </summary>
        public static string SortingStartedText {
            get {
                return ResourceManager.GetString("SortingStartedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Speed regulator.
        /// </summary>
        public static string SpeedRegulatorText {
            get {
                return ResourceManager.GetString("SpeedRegulatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start sorting.
        /// </summary>
        public static string StartSortingText {
            get {
                return ResourceManager.GetString("StartSortingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop sorting.
        /// </summary>
        public static string StopSortingText {
            get {
                return ResourceManager.GetString("StopSortingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Successfully initialized array.
        /// </summary>
        public static string SuccessfullyInitializedArrayText {
            get {
                return ResourceManager.GetString("SuccessfullyInitializedArrayText", resourceCulture);
            }
        }
    }
}
