//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SorterVisualizer.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesRandomArrayCreationWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesRandomArrayCreationWindow() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SorterVisualizer.Resources.Localization.MessagesRandomArrayCreationWindow", typeof(MessagesRandomArrayCreationWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        public static string ApplyText {
            get {
                return ResourceManager.GetString("ApplyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum value cannot be equal or greater than maximum value..
        /// </summary>
        public static string ArrayRangeValidationErrorText {
            get {
                return ResourceManager.GetString("ArrayRangeValidationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Random array was successfully created.
        /// </summary>
        public static string ArraySuccessfullyCreatedText {
            get {
                return ResourceManager.GetString("ArraySuccessfullyCreatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Random array wasn&apos;t successfully created. Try again..
        /// </summary>
        public static string ArrayUnsuccessfullyCreatedText {
            get {
                return ResourceManager.GetString("ArrayUnsuccessfullyCreatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of columns.
        /// </summary>
        public static string ColumnsNumbText {
            get {
                return ResourceManager.GetString("ColumnsNumbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter a valid integer and try again.
        /// </summary>
        public static string ConvertToIntegerErrorText {
            get {
                return ResourceManager.GetString("ConvertToIntegerErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database connection.
        /// </summary>
        public static string DatabaseConnectionText {
            get {
                return ResourceManager.GetString("DatabaseConnectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The required database does not exist.
        /// </summary>
        public static string DatabaseDoesntExistText {
            get {
                return ResourceManager.GetString("DatabaseDoesntExistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set parameters for array, that will be inserted into database:.
        /// </summary>
        public static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum value.
        /// </summary>
        public static string MaxValueText {
            get {
                return ResourceManager.GetString("MaxValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum value.
        /// </summary>
        public static string MinValueText {
            get {
                return ResourceManager.GetString("MinValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operation result.
        /// </summary>
        public static string OperationResultText {
            get {
                return ResourceManager.GetString("OperationResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rows and columns cannot be greater than 1000 or less than 1. Try again..
        /// </summary>
        public static string RowsAndColumnsValidationErrorText {
            get {
                return ResourceManager.GetString("RowsAndColumnsValidationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of rows.
        /// </summary>
        public static string RowsNumbText {
            get {
                return ResourceManager.GetString("RowsNumbText", resourceCulture);
            }
        }
    }
}
